### ISSUE TITLE
Help needed: Cups Configuration (ACLs)

### ISSUE THREAD

**Issue by jaykijay** [attah/harbour-seaprint#22]
Hi, 
thank you for this wonderful app!
As my printer only supports jpeg via ipp and even that's not working good I'm trying to use my Linux Server for this.
It runs a cups instance and as i read it should be supported by this App.
I changed the listener to listen on any interface and set Browse to "on" as suggested,
but it still keeps not working. The app does not find cups at all, not even if i enter IP and Port in this App.
I think it's an access Control issue, but as i don't have any clue and don't understand anything in the cups Config file i'm asking for help here.
Can someone provide me with an hint what has to be changed in Standard cups Config file to allow this App?

Seaprint outputs following line btw:
`[D] IppPrinter::getPrinterAttributesFinished:96 - QNetworkReply::NetworkError(ContentOperationNotPermittedError) "Error transferring http://192.168.0.101:631 - server replied: Forbidden" ""`

I'm appreciating any help :)

**Comment by attah** [comment]
Hi

I won't pretend to be a CUPS expert, because i'm not. :)
Try to point a web browser to port 631 on that machine and see what happens. Here you will also (once/if you get in) be able to find the printer name which is a required part of the url. 
A complete address is something like ipp://192.168.0.101:631:631/printers/OKI-DATA-CORP-B2200
But it looks looks like something is responding, so that's a good start.

I have this section in my cupsd.conf, apart from what i remember changing, not sure if it is related:
```
<Location />
  Order allow,deny
  Allow All
</Location>
```
I also assume you restarted CUPS to make it re-read the config file after any changes.

**Comment by jaykijay** [comment]
Thanks, i got it working ;)

Changed the section you mentioned to:
```
<Location />
    Allow localhost
    Allow 192.168.0.*
  Order allow,deny
</Location>
```
and added user "nemo" to allowd users to print for this specific printer. After this i entered the URL you mentioned (inserting the Printer Name there was the trick ;)) 
and got it printing :)

Thank you (; 
:+1:

**Comment by attah** [comment]
Good, putting that in the app description in store.
