### ISSUE TITLE
Sometimes it take a time if the printer is found.

### ISSUE THREAD

**Issue by wheelseal** [attah/harbour-seaprint#52]
Sometimes it takes a few seconds after starting Seaprint if the printer is found. In some cases it will only find them after I tap on refresh.
SailfishOS 4.3

**Comment by attah** [comment]
It is indeed not super fast. From my tests it is mostly in the printer.
I.e. CUPS/ippserver is near-instant to show up, and my OKI takes about 2 seconds.
The discovery is done via UDP and is thus unacknowledged, so if one or both devices are on WiFi, every so often a packet gets lost.

The app could probably be a bit faster (but probably not noticeable), and have retry-heuristics for discovery... but i don't think i have higher ambitions right now.

**Comment by wheelseal** [comment]
All right. Thanks for your answer. I wrote this bug-report also because Seaprint 0.9.6 was faster finding my printer as Seaprint 1.0.

Am Montag, 13. Dezember 2021 schrieb attah:
> It is indeed not super fast. From my tests it is mostly in the printer.
> I.e. CUPS/ippserver is near-instant to show up, and my OKI takes about 2 seconds.
> The discovery is done via UDP and is thus unacknowledged, so if one or both devices are on WiFi, every so often a packet gets lost.
> 
> The app could probably be a bit faster (but probably not noticeable), and have retry-heuristics for discovery... but i don't think i have higher ambitions right now.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/attah/harbour-seaprint/issues/52#issuecomment-99276828

-- 
Mit freundlichen Grüßen 

Sebastian Kergaßner

**Comment by attah** [comment]
You were right! 
The printer is slow, but the better part of one second was due to how the new http client interacts with it.
cURL really tries to follow the standard, but most things now de-facto doesn't, so it just ends up waiting too much.

Fixed here: https://github.com/attah/harbour-seaprint/commit/79e7175f87c3078009be16dbfdca4e14a3eae5ec
Background: https://daniel.haxx.se/blog/2020/02/27/expect-tweaks-in-curl/

I'll wait with releasing this a while so any bugs with the new http client are reported when it is still on its best behaviour.

**Comment by wheelseal** [comment]
👍good job. I installed the Updated version 1.0.1 from the store and the printer is found in 2-3 seconds. First i thought firejail was the problem but now i know it wasn't. 

Am Dienstag, 14. Dezember 2021 schrieb attah:
