### ISSUE TITLE
SeaPrint 1.2.4: Manuelly setting up the page range is confusing

### ISSUE THREAD

**Issue by wheelseal** [attah/harbour-seaprint#78]
On the "Printer settings" Page:
Point "Page range" (line 508 in translation page): 
Setting the page range via the slider works fine:
![Page range 1](https://user-images.githubusercontent.com/61382908/221361215-240c8259-3632-445d-9cec-55bf66de1412.jpeg)

But after I do it and tap the stylus, my selected page is not displayed:
![Page range 2](https://user-images.githubusercontent.com/61382908/221361340-89f9eb70-9885-4531-918e-93f3e1dab3f4.jpeg)

The "Page Range" hint is not displayed until I enter a number:
![Page range 3](https://user-images.githubusercontent.com/61382908/221361680-ec454523-8cb3-46f9-924c-7e07320b29dd.jpeg)

The hint "page range" should be replaced with "First page" or "Last page" and under the line it should be displayed permanently. Your example numbers 1-12 should also be replace with "First Page" or "Last Page". 
Alternatively, it could be "Page Area - First Page" or "Page Area - Last Page", which would be even clearer.

**Comment by attah** [comment]
The position on translation page is irrelevant for reporting UI bugs.
It seems i meant to keep input as prefilled value on the keyboard input page; but actually the current behaviour is better.
The 1-12 is the accepted range for your specific document, i.e. not an example, and that is really good information.
For non-pdfs i'll make sure it says "..." instead of 65535.

Why the bottom label is not displayed until you interact with it, i don't know. That looks like a bug in Jolla's Silica UI stuff and is beyond my control.
I will be adding High and Low to the label to make it more clear. But i think it is good that it still says what you are setting too.

The term "Page area" is not understandable.

**Comment by wheelseal** [comment]
> The position on translation page is irrelevant for reporting UI bugs.

I Know but i thought it is easier to find for you ;)


> The 1-12 is the accepted range for your specific document, i.e. not an example, and that is really good information.

Yes, that is good information. I misunderstood because I tried it with only one document with 12 pages and mistakenly thought it was meant as an example for all documents. 


> Why the bottom label is not displayed until you interact with it, i don't know. That looks like a bug in Jolla's Silica UI stuff and is beyond my control.

i Understand.



> I will be adding High and Low to the label to make it more clear. But i think it is good that it still says what you are setting too.

Why High and Low? First and Last not better?

> The term "Page area" is not understandable.

That´s right, it was a mistake of me. Of course I mean "Page Range".

**Comment by attah** [comment]
> Why High and Low? First and Last not better?

The component is generic to all ranges... so something generic just made more sense to me.
(The name of the setting itself is parameterized)
Realistically there will be no other ranges most likely, but none the less, that was my reasoning.
I think it is good enough... but will think on it some more.
