### ISSUE TITLE
Gradient in the marker for the black toner.

### ISSUE THREAD

**Issue by wheelseal** [attah/harbour-seaprint#83]
It seems that the marker for the black toner has a color gradient. This gives the impression that this marker is smaller than the others. Please remove it. I am using SfOS 4.6.0.13.

**Comment by attah** [comment]
There is no such thing as "the *indicator* for the black toner". It is just one component which is reused/parameterized for all supplies. It has a slight glass effect overlaid to show where 100% is, and also because it looks good. For obvious reasons that is implemented in transparency and grayscale, so it has a bit of a more drastic effect on black. It also looks much better on a display that isn't tuned to over-saturation to brag about being OLED. In fact the black looks exactly like i want it, whereas the others don't have enough of a glass effect. But i'm no graphic designer, and this is the best i could do with reasonable time.

Please stop telling me how to do things. Just report the problem and leave it at that.
